version: 3
pullapprove_conditions:
- condition: "'WIP' in title"
  unmet_status: pending
  explanation: "Work in progress"
groups:
  code:
    reviews:
      required: 2  # number of approvals required from this group
      request: 1  # number of review requests sent at a time
      request_order: random  # "random" or "given"
    labels:
      approved: "Code review approved"

